<!DOCTYPE html>
<html>
  <head>
    <title>Random Quote Generator</title>
    <link rel="stylesheet" type="text/css" href="./style.css">
  </head>

  <body>
    <div id="quote_block">
      <h1 id="rand_quote_gen_title">Quote of the Day:</h1>

      <?php require_once('./random_quote_generator.php'); ?>


      <!-- Generated by PHP: <blockquote cite="generated" -->

      <?php echo $quote_cite_tag_value ?>
      <h2 id="quote"><em><?php echo $quote_text;?></em></h2>
      <p id="author"><strong>- <?php echo $quote_author ?></strong></p>
      </blockquote>
    </div>


  </body>
</html>
